apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    env: test
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["sleep"]
    args: ["3600"]
  nodeSelector:
    kubernetes.io/hostname: gke-chrismark-elasticon-default-pool-d8304c2d-thhk
