apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: flaskapi
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi-deployment
  labels:
    app: flaskapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapi
  template:
    metadata:
      labels:
        app: flaskapi
    spec:
      volumes:
      - name: proc
        hostPath:
          path: /proc
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        kubernetes.io/hostname: gke-chrismark-elasticon-default-pool-d8304c2d-thhk
      containers:
        - name: flaskapi
          image: chrismark/flaskapi:v1.0.0
          volumeMounts:
          - name: proc
            mountPath: /hostfs/proc
            readOnly: true
